### ISSUE TITLE
Crash when tapping Favorites

### ISSUE THREAD

**Issue by nicnocquee** [ay8s/ShutterSpots-Issues#14]

**Comment by tommoor** [comment]
Repro steps? Not happening here.

**Comment by nicnocquee** [comment]
I just tapped the Favorite tab. Probably because I favorited a spot before in the previous version.

**Comment by ay8s** [comment]
Fixed up some potential issues in all of the tabs that might fix this up. Closing for now.

**Comment by nicnocquee** [comment]
Just to let you know, this still happens in 1.0.2. Hope you're getting the crash report :)
